# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K9sAi < Formula
  desc "K9s AI — Kubernetes CLI with built-in AI/Copilot assistant"
  homepage "https://github.com/orshohat1/k9s-ai"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/orshohat1/k9s-ai/releases/download/v0.1.0/k9s-ai_Darwin_amd64.tar.gz"
      sha256 "39c2beeb7911369f8199440279d7ba7a2255eedde5ec38b1a51529ba942dec5a"

      define_method(:install) do
        bin.install "k9s-ai"
        generate_completions_from_executable(bin/"k9s-ai", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/orshohat1/k9s-ai/releases/download/v0.1.0/k9s-ai_Darwin_arm64.tar.gz"
      sha256 "e365a7aea0398435e052138ac9bcb6fe3a02e16c7e784ca7dee687bd410cad21"

      define_method(:install) do
        bin.install "k9s-ai"
        generate_completions_from_executable(bin/"k9s-ai", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/orshohat1/k9s-ai/releases/download/v0.1.0/k9s-ai_Linux_amd64.tar.gz"
      sha256 "d88061717085651bd5e71f4d62e6df393cec0ed509d1510b1677c8fed3aeaad4"
      define_method(:install) do
        bin.install "k9s-ai"
        generate_completions_from_executable(bin/"k9s-ai", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/orshohat1/k9s-ai/releases/download/v0.1.0/k9s-ai_Linux_arm64.tar.gz"
      sha256 "57fa3d7ca792f173af071c458156c7d95241c5b10dd1802b2546ce8e393961a3"
      define_method(:install) do
        bin.install "k9s-ai"
        generate_completions_from_executable(bin/"k9s-ai", "completion")
      end
    end
  end

  test do
    system "#{bin}/k9s-ai", "version"
  end
end
