# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K9sAi < Formula
  desc "K9s AI — Kubernetes CLI with built-in AI/Copilot assistant"
  homepage "https://github.com/orshohat1/k9s-ai"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/orshohat1/k9s-ai/releases/download/v0.1.0/k9s-ai_Darwin_amd64.tar.gz"
      sha256 "0582129dba05cdb23295f5564e2ff3b06ad996a65af8bd9f5878cc10594f086a"

      define_method(:install) do
        bin.install "k9s-ai"
        generate_completions_from_executable(bin/"k9s-ai", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/orshohat1/k9s-ai/releases/download/v0.1.0/k9s-ai_Darwin_arm64.tar.gz"
      sha256 "a380564fc2b3985e87efc25bde9d518020d901350d3a0178424e691a04d8cf98"

      define_method(:install) do
        bin.install "k9s-ai"
        generate_completions_from_executable(bin/"k9s-ai", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/orshohat1/k9s-ai/releases/download/v0.1.0/k9s-ai_Linux_amd64.tar.gz"
      sha256 "eece469f644f91b66bdb1c2694ebebe647216505de2f6a877af71dc4cf505261"
      define_method(:install) do
        bin.install "k9s-ai"
        generate_completions_from_executable(bin/"k9s-ai", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/orshohat1/k9s-ai/releases/download/v0.1.0/k9s-ai_Linux_arm64.tar.gz"
      sha256 "0ef97845c1dbd20b471ca693cd3d535d1eade9b3ed1cdaa42c60727f553959bc"
      define_method(:install) do
        bin.install "k9s-ai"
        generate_completions_from_executable(bin/"k9s-ai", "completion")
      end
    end
  end

  test do
    system "#{bin}/k9s-ai", "version"
  end
end
