# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K9sAi < Formula
  desc "K9s AI — Kubernetes CLI with built-in AI/Copilot assistant"
  homepage "https://github.com/orshohat1/k9s-ai"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/orshohat1/k9s-ai/releases/download/v0.1.1/k9s-ai_Darwin_amd64.tar.gz"
      sha256 "078474f1926d5b123990defbbfc1a58894adf364ace208a3564ccd47787f1820"

      define_method(:install) do
        bin.install "k9s-ai"
        generate_completions_from_executable(bin/"k9s-ai", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/orshohat1/k9s-ai/releases/download/v0.1.1/k9s-ai_Darwin_arm64.tar.gz"
      sha256 "b468e0b60ff0647445364b9ad6182770441380f02e74e90328cfec37c318bedf"

      define_method(:install) do
        bin.install "k9s-ai"
        generate_completions_from_executable(bin/"k9s-ai", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/orshohat1/k9s-ai/releases/download/v0.1.1/k9s-ai_Linux_amd64.tar.gz"
      sha256 "cbd459bdec8acaf9f4961afc2accf364295a4bd182f18d7f6486381e0c37aa08"
      define_method(:install) do
        bin.install "k9s-ai"
        generate_completions_from_executable(bin/"k9s-ai", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/orshohat1/k9s-ai/releases/download/v0.1.1/k9s-ai_Linux_arm64.tar.gz"
      sha256 "c7caba4c2f89b517a44545e3daf0db4df381fced29c301b758171045c4e64df6"
      define_method(:install) do
        bin.install "k9s-ai"
        generate_completions_from_executable(bin/"k9s-ai", "completion")
      end
    end
  end

  test do
    system "#{bin}/k9s-ai", "version"
  end
end
